---
on: [push]  # yamllint disable-line rule:truthy

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: damfle/github-action-yamllint@v1.0.2
        with:
          file_or_dir: ./
          strict: true
